// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ59FnKwKvtegaZ-q_ERhTFY54ytEGink',
    appId: '1:81730217503:web:049762b632525694a9972a',
    messagingSenderId: '81730217503',
    projectId: 'studymate-22c94',
    authDomain: 'studymate-22c94.firebaseapp.com',
    storageBucket: 'studymate-22c94.firebasestorage.app',
    measurementId: 'G-K6LN11QVMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJFgRhTkKlfeBbb-qVA2HrPjfHi6uzH5I',
    appId: '1:81730217503:android:aeb0ce57c9308e69a9972a',
    messagingSenderId: '81730217503',
    projectId: 'studymate-22c94',
    storageBucket: 'studymate-22c94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBts_1e2uZScpY4ZsZvz6R85lvSN0cT9zg',
    appId: '1:81730217503:ios:24a533e077cf673aa9972a',
    messagingSenderId: '81730217503',
    projectId: 'studymate-22c94',
    storageBucket: 'studymate-22c94.firebasestorage.app',
    iosBundleId: 'com.example.studyMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBts_1e2uZScpY4ZsZvz6R85lvSN0cT9zg',
    appId: '1:81730217503:ios:24a533e077cf673aa9972a',
    messagingSenderId: '81730217503',
    projectId: 'studymate-22c94',
    storageBucket: 'studymate-22c94.firebasestorage.app',
    iosBundleId: 'com.example.studyMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ59FnKwKvtegaZ-q_ERhTFY54ytEGink',
    appId: '1:81730217503:web:cda460bb386e7bb4a9972a',
    messagingSenderId: '81730217503',
    projectId: 'studymate-22c94',
    authDomain: 'studymate-22c94.firebaseapp.com',
    storageBucket: 'studymate-22c94.firebasestorage.app',
    measurementId: 'G-LYW71X3NSB',
  );
}
